services:
  foss-seeder:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: foss-seeder
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/app/data
    environment:
      - PORT=7474
